// <auto-generated />
using System;
using Darts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Darts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DartsDbContext))]
    [Migration("20260703104728_RemoveMatchInputSource")]
    partial class RemoveMatchInputSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Darts.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WinnerPlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WinnerPlayerIds");

                    b.HasKey("Id");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Darts.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Darts.Domain.Entities.ThrowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LegNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<string>("RawNotation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ring")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Segment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Sequence");

                    b.ToTable("ThrowRecords", (string)null);
                });

            modelBuilder.Entity("Darts.Domain.Entities.Match", b =>
                {
                    b.OwnsMany("Darts.Domain.Entities.MatchParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("FinalPosition")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("GroupIndex")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MatchId", "Order");

                            b1.ToTable("MatchParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
